#!/usr/bin/env bash
#
# Super installation script

set -e

# --------------–-------–--------–--------–-------–--–-----
# OSX defaults
# --------------–-------–--------–--------–-------–--–-----

OSX=$(test "`uname`" == "Darwin" && echo "x")

# Install osx defaults
if [[ OSX ]]; then
  ./osx/defaults
fi

# --------------–-------–--------–--------–-------–--–-----
# Vim Configuration
# --------------–-------–--------–--------–-------–--–-----

# Create vim folder
mkdir ~/.vim

# Install vim plugin manager
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

# Create .vimrc
mv ./vim/vimrc ~/.vimrc
