#!/usr/bin/env bash
#
# Super installation script

set -e

# --------------–-------–--------–--------–-------–--–-----
# System packages
# --------------–-------–--------–--------–-------–--–-----

# Install Homebrew for package management, if not installed
if test ! $(which brew)
then
  echo " ===> Installing Homebrew for package management..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Make sure Homebrew is up to date
brew update
brew upgrade

# Install all packages listed in the brewfile
brew install $(cat brew/brewfile | grep -v "#")

# --------------–-------–--------–--------–-------–--–-----
# OSX defaults
# --------------–-------–--------–--------–-------–--–-----

OSX=$(test "`uname`" == "Darwin" && echo "x")

# Install osx defaults
if [[ OSX ]]; then
  ./osx/defaults
fi

# --------------–-------–--------–--------–-------–--–-----
# Vim Configuration
# --------------–-------–--------–--------–-------–--–-----

# Create vim folder
mkdir ~/.vim

# Install vim plugin manager
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

# Create .vimrc
mv ./vim/vimrc ~/.vimrc
