#!/usr/bin/env bash
#
# Super installation script

set -e

# --------------–-------–--------–--------–-------–--–-----
# System packages
# --------------–-------–--------–--------–-------–--–-----

# Install Homebrew for package management, if not installed
if test ! $(which brew)
then
  echo "→ Installing Homebrew for package management..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Make sure Homebrew is up to date
brew update
brew upgrade

# Install all packages listed in the brewfile
brew install $(cat brew/brewfile | grep -v "#")

# --------------–-------–--------–--------–-------–--–-----
# OSX defaults
# --------------–-------–--------–--------–-------–--–-----

OSX=$(test "`uname`" == "Darwin" && echo "x")

# Install osx defaults
if [[ OSX ]]; then
  ./osx/defaults
fi

# --------------–-------–--------–--------–-------–--–-----
# Fish
# --------------–-------–--------–--------–-------–--–-----

# Install oh-my-fish
echo "→ Installing oh-my-fish..."
curl -L http://get.oh-my.fish | fish

# Install Fisherman, a plugin manager for Fish
echo "→ Installing Fisherman, a plugin manager for Fish..."
curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisherman

# Set Fish as default shell
echo "→ Linking Fish dotfiles..."
sudo echo /usr/local/bin/fish >> /etc/shells
chsh -s /usr/local/bin/fish

# Link Fish dotfiles
ln -s ~/dotfiles/fish/config.fish ~/.config/fish/conf.d/config.fish
ln -s ~/dotfiles/fish/utils ~/.config/fish/custom
ln -s ~/dotfiles/fish/fishfile ~/.config/fish/fishfile

# Run fisher
fisher

# --------------–-------–--------–--------–-------–--–-----
# Vim Configuration
# --------------–-------–--------–--------–-------–--–-----

# Create vim folder
mkdir ~/.vim

# Install vim plugin manager
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

# Create .vimrc
mv ./vim/vimrc ~/.vimrc
